name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    runs-on: ubuntu-24.04-arm
    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - name: Install dependencies
      run: cargo install cargo-tarpaulin
    - name: Build
      run: cargo build --verbose
    - name: Format
      run: cargo fmt -- --check
    - name: Clippy
      run: cargo clippy -- -D warnings
    - name: Test
      run: cargo test --verbose
    - name: Run tarpaulin
      run: cargo tarpaulin --verbose --out Xml
    - name: Upload coverage
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
